name: Canary Debian Trixie image

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  upload:
    uses: proof-computer/liskov-github-actions/.github/workflows/runtime-image.yml@v1
    with:
      application-id: liskov-runtime-images-v5-canary
      manifest-path: .liskov/canary-debian-trixie.json
      image-url: https://github.com/proof-computer/liskov-runtime-images/releases/download/v0.1.0-rc.1/liskov-runtime-image-debian-trixie-aarch64.tar.xz
      expected-sha256: 976a99022d24a3940d5175281141869703b6f503c2e3e194f107bd4a3e1ffa6d
