name: Canary Debian Trixie image

on:
  workflow_dispatch:

permissions:
  attestations: read
  contents: read
  id-token: write

jobs:
  upload:
    uses: proof-computer/liskov-github-actions/.github/workflows/runtime-image.yml@v1
    with:
      application-id: liskov-runtime-images-v5-canary
      manifest-path: .liskov/canary-debian-trixie.json
      image-url: https://github.com/proof-computer/liskov-runtime-images/releases/download/v0.1.0-rc.11/liskov-runtime-image-debian-trixie-aarch64.tar.xz
      expected-sha256: 97523a10978903fe63bb0df55fc0be411a137a101d2697a3d866c2abb1a0ddf4
      attestation-repository: proof-computer/liskov-runtime-images
      attestation-source-digest: 324c6f8b756c26fedb3fdf24463818d629203e78
      attestation-signer-workflow: proof-computer/liskov-runtime-images/.github/workflows/ci.yml
